// The `enhanceUserInputWithWebsiteContent` flow enhances user input with content from a relevant website, using a tool to retrieve website content.
//
// - enhanceUserInputWithWebsiteContent - A function that takes user input and enriches it with website content using an LLM.
// - EnhanceUserInputWithWebsiteContentInput - The input type for the enhanceUserInputWithWebsiteContent function.
// - EnhanceUserInputWithWebsiteContentOutput - The return type for the enhanceUserInputWithWebsiteContent function.

'use server';
import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { devConsole } from '@/lib/console';

const EnhanceUserInputWithWebsiteContentInputSchema = z.object({
  userInput: z.string().describe('The user input to enhance with website content.'),
});

export type EnhanceUserInputWithWebsiteContentInput = z.infer<typeof EnhanceUserInputWithWebsiteContentInputSchema>;

const EnhanceUserInputWithWebsiteContentOutputSchema = z.object({
  enhancedContent: z.string().describe('The enhanced content generated by the LLM.'),
});

export type EnhanceUserInputWithWebsiteContentOutput = z.infer<typeof EnhanceUserInputWithWebsiteContentOutputSchema>;

export async function enhanceUserInputWithWebsiteContent(input: EnhanceUserInputWithWebsiteContentInput): Promise<EnhanceUserInputWithWebsiteContentOutput> {
  return enhanceUserInputWithWebsiteContentFlow(input);
}

const getWebsiteContent = ai.defineTool({
  name: 'getWebsiteContent',
  description: 'Retrieves the content of a website given its URL.',
  inputSchema: z.object({
    url: z.string().url().describe('The URL of the website to retrieve content from.'),
  }),
  outputSchema: z.string(),
}, async (input) => {
  try {
    const response = await fetch(input.url);
    if (!response.ok) {
      throw new Error(`HTTP error! Status: ${response.status}`);
    }
    return await response.text();
  } catch (error) {
    devConsole.error('Failed to fetch website content:', error);
    return 'Failed to retrieve website content.';
  }
});

const enhanceUserInputWithWebsiteContentPrompt = ai.definePrompt({
  name: 'enhanceUserInputWithWebsiteContentPrompt',
  input: {schema: EnhanceUserInputWithWebsiteContentInputSchema},
  output: {schema: EnhanceUserInputWithWebsiteContentOutputSchema},
  tools: [getWebsiteContent],
  prompt: `You are an AI assistant that enhances user input with relevant content from the web.

  User Input: {{{userInput}}}

  If the user input mentions a topic that could be expanded with information from a website, use the getWebsiteContent tool to retrieve content from a relevant website.
  Include the relevant content from the website in your response to enhance the user input.

  If you use the getWebsiteContent tool, make sure to cite the source URL.

  Enhanced Content:`,config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_NONE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
    ],
  },
});

const enhanceUserInputWithWebsiteContentFlow = ai.defineFlow({
    name: 'enhanceUserInputWithWebsiteContentFlow',
    inputSchema: EnhanceUserInputWithWebsiteContentInputSchema,
    outputSchema: EnhanceUserInputWithWebsiteContentOutputSchema,
  },
  async input => {
    const {output} = await enhanceUserInputWithWebsiteContentPrompt(input);
    return output!;
  }
);
