/**
 * GitHub Integration for Autofix
 *
 * Creates branches, commits fixes, and opens PRs using the GitHub API.
 * Uses the user's stored GitHub OAuth token (repo scope).
 */

import { db } from '@/lib/firebase/admin';
import { GeneratedFix } from './types';
import { logger } from '@/lib/logger';

const GITHUB_API = 'https://api.github.com';

interface GitHubConnection {
  accessToken: string;
  refreshToken?: string;
  expiresAt?: string;
}

/**
 * Get the user's GitHub access token from Firestore
 */
export async function getGitHubToken(userId: string): Promise<string> {
  const doc = await db.collection('githubConnections').doc(userId).get();
  if (!doc.exists) {
    throw new Error('GitHub not connected. Please connect GitHub in Settings.');
  }

  const conn = doc.data() as GitHubConnection;

  // Check if token is expired and needs refresh
  if (conn.expiresAt && new Date(conn.expiresAt) < new Date()) {
    if (!conn.refreshToken) {
      throw new Error('GitHub token expired. Please reconnect GitHub in Settings.');
    }
    // Token refresh is handled by the OAuth module
    throw new Error('GitHub token expired. Please reconnect GitHub in Settings.');
  }

  return conn.accessToken;
}

/**
 * Get repository info (default branch, etc.)
 */
export async function getRepoInfo(
  token: string,
  owner: string,
  repo: string
): Promise<{ defaultBranch: string; fullName: string }> {
  const resp = await fetch(`${GITHUB_API}/repos/${owner}/${repo}`, {
    headers: ghHeaders(token),
  });

  if (!resp.ok) {
    if (resp.status === 404) throw new Error(`Repository ${owner}/${repo} not found or not accessible`);
    throw new Error(`GitHub API error: ${resp.status}`);
  }

  const data = await resp.json();
  return {
    defaultBranch: data.default_branch,
    fullName: data.full_name,
  };
}

/**
 * Create a branch for autofix, commit all fixes, and optionally open a PR.
 * One branch per scan run — all fixes in a single branch.
 */
export async function pushFixBranch(options: {
  token: string;
  owner: string;
  repo: string;
  baseBranch: string;
  branchName: string;
  scanId: string;
  fixes: GeneratedFix[];
  createPR: boolean;
  /** Custom PR title (defaults to autofix title) */
  prTitle?: string;
  /** Custom PR body (defaults to autofix body) */
  prBody?: string;
}): Promise<{
  branch: string;
  commitSha: string;
  filesChanged: number;
  prUrl?: string;
  prNumber?: number;
}> {
  const { token, owner, repo, baseBranch, branchName, scanId, fixes, createPR, prTitle, prBody } = options;

  // 1. Get the latest commit SHA of the base branch
  const baseRef = await getRef(token, owner, repo, `heads/${baseBranch}`);

  // 2. Get the base tree
  const baseCommit = await getCommit(token, owner, repo, baseRef);
  const baseTree = baseCommit.tree.sha;

  // 3. Create blobs for each fixed file
  const treeEntries = await Promise.all(
    fixes.map(async (fix) => {
      const blob = await createBlob(token, owner, repo, fix.fixedContent);
      return {
        path: fix.file,
        mode: '100644' as const,
        type: 'blob' as const,
        sha: blob.sha,
      };
    })
  );

  // 4. Create a new tree with all fixes
  const newTree = await createTree(token, owner, repo, baseTree, treeEntries);

  // 5. Build commit message with all findings fixed
  const findingSummary = fixes
    .map(f => `- ${f.explanation}`)
    .slice(0, 20)
    .join('\n');
  const remaining = fixes.length > 20 ? `\n... and ${fixes.length - 20} more fixes` : '';

  const commitMessage = `fix: autofix ${fixes.length} findings from Bugrit scan ${scanId}

${findingSummary}${remaining}

Generated by Bugrit Autofix
Scan: ${scanId}`;

  // 6. Create the commit
  const commit = await createCommitObj(token, owner, repo, commitMessage, newTree.sha, baseRef);

  // 7. Create the branch pointing to our commit
  await createBranchRef(token, owner, repo, branchName, commit.sha);

  // 8. Optionally create a PR
  let prUrl: string | undefined;
  let prNumber: number | undefined;

  if (createPR) {
    const pr = await createPullRequest(token, owner, repo, {
      title: prTitle || `fix: Bugrit autofix — ${fixes.length} findings (scan ${scanId.substring(0, 8)})`,
      body: prBody || buildPRBody(scanId, fixes),
      head: branchName,
      base: baseBranch,
    });
    prUrl = pr.html_url;
    prNumber = pr.number;
  }

  return {
    branch: branchName,
    commitSha: commit.sha,
    filesChanged: fixes.length,
    prUrl,
    prNumber,
  };
}

// ═══════════════════════════════════════════════════════════════
// GitHub API Helpers
// ═══════════════════════════════════════════════════════════════

function ghHeaders(token: string): Record<string, string> {
  return {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github.v3+json',
    'X-GitHub-Api-Version': '2022-11-28',
  };
}

async function getRef(token: string, owner: string, repo: string, ref: string): Promise<string> {
  const resp = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/git/ref/${ref}`, {
    headers: ghHeaders(token),
  });
  if (!resp.ok) throw new Error(`Failed to get ref ${ref}: ${resp.status}`);
  const data = await resp.json();
  return data.object.sha;
}

async function getCommit(token: string, owner: string, repo: string, sha: string) {
  const resp = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/git/commits/${sha}`, {
    headers: ghHeaders(token),
  });
  if (!resp.ok) throw new Error(`Failed to get commit ${sha}: ${resp.status}`);
  return resp.json();
}

async function createBlob(token: string, owner: string, repo: string, content: string) {
  const resp = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/git/blobs`, {
    method: 'POST',
    headers: ghHeaders(token),
    body: JSON.stringify({ content, encoding: 'utf-8' }),
  });
  if (!resp.ok) throw new Error(`Failed to create blob: ${resp.status}`);
  return resp.json();
}

async function createTree(
  token: string,
  owner: string,
  repo: string,
  baseTree: string,
  entries: Array<{ path: string; mode: '100644'; type: 'blob'; sha: string }>
) {
  const resp = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/git/trees`, {
    method: 'POST',
    headers: ghHeaders(token),
    body: JSON.stringify({ base_tree: baseTree, tree: entries }),
  });
  if (!resp.ok) throw new Error(`Failed to create tree: ${resp.status}`);
  return resp.json();
}

async function createCommitObj(
  token: string,
  owner: string,
  repo: string,
  message: string,
  tree: string,
  parent: string
) {
  const resp = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/git/commits`, {
    method: 'POST',
    headers: ghHeaders(token),
    body: JSON.stringify({ message, tree, parents: [parent] }),
  });
  if (!resp.ok) throw new Error(`Failed to create commit: ${resp.status}`);
  return resp.json();
}

async function createBranchRef(token: string, owner: string, repo: string, branch: string, sha: string) {
  const resp = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/git/refs`, {
    method: 'POST',
    headers: ghHeaders(token),
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha }),
  });
  if (!resp.ok) {
    const errBody = await resp.text();
    // If branch already exists, update it
    if (resp.status === 422 && errBody.includes('Reference already exists')) {
      const updateResp = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/git/refs/heads/${branch}`, {
        method: 'PATCH',
        headers: ghHeaders(token),
        body: JSON.stringify({ sha, force: true }),
      });
      if (!updateResp.ok) throw new Error(`Failed to update branch ${branch}: ${updateResp.status}`);
      return updateResp.json();
    }
    throw new Error(`Failed to create branch ${branch}: ${resp.status} — ${errBody}`);
  }
  return resp.json();
}

async function createPullRequest(
  token: string,
  owner: string,
  repo: string,
  pr: { title: string; body: string; head: string; base: string }
) {
  const resp = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/pulls`, {
    method: 'POST',
    headers: ghHeaders(token),
    body: JSON.stringify(pr),
  });
  if (!resp.ok) {
    const errBody = await resp.text();
    throw new Error(`Failed to create PR: ${resp.status} — ${errBody}`);
  }
  return resp.json();
}

/**
 * Fetch a file's content from the repo
 */
export async function getFileContent(
  token: string,
  owner: string,
  repo: string,
  path: string,
  ref: string
): Promise<string | null> {
  const resp = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/contents/${encodeURIComponent(path)}?ref=${ref}`, {
    headers: ghHeaders(token),
  });

  if (!resp.ok) return null;
  const data = await resp.json();
  if (data.encoding === 'base64') {
    return Buffer.from(data.content, 'base64').toString('utf-8');
  }
  return data.content || null;
}

// ═══════════════════════════════════════════════════════════════
// PR Body Builder
// ═══════════════════════════════════════════════════════════════

function buildPRBody(scanId: string, fixes: GeneratedFix[]): string {
  const byFile = new Map<string, GeneratedFix[]>();
  for (const fix of fixes) {
    const existing = byFile.get(fix.file) || [];
    existing.push(fix);
    byFile.set(fix.file, existing);
  }

  const fileList = Array.from(byFile.entries())
    .map(([file, fileFixes]) =>
      `- \`${file}\` — ${fileFixes.length} fix${fileFixes.length > 1 ? 'es' : ''}`
    )
    .join('\n');

  const highConfidence = fixes.filter(f => f.confidence === 'high').length;
  const medConfidence = fixes.filter(f => f.confidence === 'medium').length;
  const lowConfidence = fixes.filter(f => f.confidence === 'low').length;

  return `## Bugrit Autofix

Automated code fixes generated from Bugrit scan \`${scanId}\`.

### Summary
- **${fixes.length}** findings fixed across **${byFile.size}** files
- Confidence: ${highConfidence} high, ${medConfidence} medium, ${lowConfidence} low

### Files Changed
${fileList}

### Fix Details
${fixes.slice(0, 30).map(f => `- **${f.file}**: ${f.explanation}`).join('\n')}
${fixes.length > 30 ? `\n... and ${fixes.length - 30} more fixes` : ''}

---
*Generated by [Bugrit Autofix](https://bugrit.dev) — AI-powered security fixes*
*Scan ID: \`${scanId}\`*

> **Review carefully before merging.** AI-generated fixes should be verified by a human.`;
}
